//RECIPES
export const ADD_RECIPES = "ADD_RECIPES";
export const DELETE_RECIPES = "DELETE_RECIPES";
export const GET_RECIPES = "GET_RECIPES";
export const RECIPES_LOADING = "RECIPES_LOADING";
export const LOOKUP_RECIPES = "LOOKUP_RECIPES";
export const EMPTY_DATA = "EMPTY_DATA";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
